"""
deployment_example.py — Streamlit app for DOGE next-day price prediction
─────────────────────────────────────────────────────────────────────────
Folder layout expected in your repo:
  ├── deployment_example.py       ← this file
  ├── requirements.txt            ← generated by the notebook export cell
  └── model_artifacts/
        ├── ensemble_rf_gbr.joblib
        ├── scaler.joblib
        ├── feature_columns.joblib
        └── model_metadata.json

Run locally : streamlit run deployment_example.py
Deploy      : push repo to GitHub → connect on share.streamlit.io
"""

import os, json
import numpy as np
import pandas as pd
import requests
import joblib
import streamlit as st
from datetime import datetime, timedelta

# ── Page config ────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="DOGE Price Predictor",
    page_icon="🚀",
    layout="centered",
)

# ── Paths ──────────────────────────────────────────────────────────────────
BASE_DIR     = os.path.dirname(os.path.abspath(__file__))
ARTIFACT_DIR = os.path.join(BASE_DIR, "model_artifacts")

MODEL_PATH    = os.path.join(ARTIFACT_DIR, "ensemble_rf_gbr.joblib")
SCALER_PATH   = os.path.join(ARTIFACT_DIR, "scaler.joblib")
FEATURES_PATH = os.path.join(ARTIFACT_DIR, "feature_columns.joblib")
META_PATH     = os.path.join(ARTIFACT_DIR, "model_metadata.json")


# ──────────────────────────────────────────────────────────────────────────
# 1.  Load artifacts (cached — only runs once per session)
# ──────────────────────────────────────────────────────────────────────────
@st.cache_resource(show_spinner="Loading model…")
def load_artifacts():
    """Load model, scaler, feature list, and metadata from disk."""
    missing = [p for p in [MODEL_PATH, SCALER_PATH, FEATURES_PATH] if not os.path.exists(p)]
    if missing:
        st.error(
            f"Missing artifact file(s): {missing}\n\n"
            "Make sure `model_artifacts/` is committed to your repo "
            "and the filenames match exactly."
        )
        st.stop()

    model    = joblib.load(MODEL_PATH)
    scaler   = joblib.load(SCALER_PATH)
    features = joblib.load(FEATURES_PATH)           # list[str]
    meta     = json.load(open(META_PATH)) if os.path.exists(META_PATH) else {}
    return model, scaler, features, meta


# ──────────────────────────────────────────────────────────────────────────
# 2.  Fetch live data from CoinGecko
# ──────────────────────────────────────────────────────────────────────────
@st.cache_data(ttl=3600, show_spinner="Fetching latest DOGE data…")
def fetch_doge(days: int = 90) -> pd.DataFrame | None:
    """Pull daily DOGE/USD data from CoinGecko public API."""
    url = (
        "https://api.coingecko.com/api/v3/coins/dogecoin/market_chart"
        f"?vs_currency=usd&days={days}&interval=daily"
    )
    try:
        r = requests.get(url, headers={"accept": "application/json"}, timeout=15)
        r.raise_for_status()
        raw = r.json()
        prices  = pd.DataFrame(raw["prices"],       columns=["ts", "close"])
        volumes = pd.DataFrame(raw["total_volumes"], columns=["ts", "volume"])
        mcaps   = pd.DataFrame(raw["market_caps"],   columns=["ts", "market_cap"])
        df = prices.merge(volumes, on="ts").merge(mcaps, on="ts")
        df["date"] = pd.to_datetime(df["ts"], unit="ms").dt.normalize()
        df = df.drop(columns=["ts"]).set_index("date").sort_index()
        return df
    except Exception as e:
        st.warning(f"CoinGecko fetch failed: {e}. Using simulated data.")
        return None


def synthetic_data(n: int = 90) -> pd.DataFrame:
    """GBM fallback when the API is unavailable."""
    dates   = pd.date_range(end=datetime.today().date(), periods=n, freq="D")
    prices  = 0.08 * np.exp(np.cumsum(np.random.normal(0.001, 0.05, n)))
    volumes = np.random.lognormal(20, 0.5, n)
    mcaps   = prices * 1.4e11
    df = pd.DataFrame({"close": prices, "volume": volumes, "market_cap": mcaps}, index=dates)
    df.index.name = "date"
    return df


# ──────────────────────────────────────────────────────────────────────────
# 3.  Feature engineering (must match notebook exactly)
# ──────────────────────────────────────────────────────────────────────────
def _rsi(s: pd.Series, w: int = 14) -> pd.Series:
    d = s.diff()
    g = d.clip(lower=0).rolling(w).mean()
    l = (-d.clip(upper=0)).rolling(w).mean()
    return 100 - 100 / (1 + g / l.replace(0, np.nan))


def build_features(df: pd.DataFrame) -> pd.DataFrame:
    """Replicate every feature from the training notebook."""
    f = df.copy()

    # Transformations
    f["daily_return"]     = f["close"].pct_change()
    f["log_daily_return"] = np.log(f["close"]).diff()
    f["volatility_7d"]    = f["log_daily_return"].rolling(7).std()
    f["volatility_30d"]   = f["log_daily_return"].rolling(30).std()
    f["volume_mcap_ratio"]= f["volume"] / f["market_cap"]

    # Lags
    for lag in range(1, 8):
        f[f"lag_{lag}"]        = f["close"].shift(lag)
        f[f"return_lag_{lag}"] = f["daily_return"].shift(lag)

    # Moving averages
    for w in [7, 14, 30]:
        f[f"sma_{w}"] = f["close"].rolling(w).mean()
    f["ema_12"] = f["close"].ewm(span=12, adjust=False).mean()
    f["ema_26"] = f["close"].ewm(span=26, adjust=False).mean()

    # MACD
    f["macd"]        = f["ema_12"] - f["ema_26"]
    f["macd_signal"] = f["macd"].ewm(span=9, adjust=False).mean()
    f["macd_hist"]   = f["macd"] - f["macd_signal"]

    # RSI
    f["rsi_14"] = _rsi(f["close"])

    # Bollinger Bands
    bb_mid         = f["close"].rolling(20).mean()
    bb_std         = f["close"].rolling(20).std()
    f["bb_upper"]  = bb_mid + 2 * bb_std
    f["bb_lower"]  = bb_mid - 2 * bb_std
    f["bb_width"]  = (f["bb_upper"] - f["bb_lower"]) / bb_mid
    f["bb_pct"]    = (f["close"] - f["bb_lower"]) / (f["bb_upper"] - f["bb_lower"] + 1e-10)

    # Volume features
    f["vol_sma_7"]  = f["volume"].rolling(7).mean()
    f["vol_sma_30"] = f["volume"].rolling(30).mean()
    f["vol_ratio"]  = f["volume"] / f["vol_sma_30"]

    # Price vs MA
    f["price_vs_sma7"]  = f["close"] / f["sma_7"]  - 1
    f["price_vs_sma30"] = f["close"] / f["sma_30"] - 1

    # Calendar
    f["day_of_week"] = f.index.dayofweek
    f["month"]       = f.index.month
    f["quarter"]     = f.index.quarter
    f["is_weekend"]  = (f["day_of_week"] >= 5).astype(int)

    return f.dropna()


# ──────────────────────────────────────────────────────────────────────────
# 4.  Streamlit UI
# ──────────────────────────────────────────────────────────────────────────
model, scaler, feature_cols, meta = load_artifacts()

st.title("🚀 DOGE Next-Day Price Predictor")
st.caption(
    f"Ensemble Random Forest + GBR  •  Trained on "
    f"{meta.get('train_period', ['?','?'])[0]} → {meta.get('train_period', ['?','?'])[1]}"
)

# ── Sidebar: model info ───────────────────────────────────────────────────
with st.sidebar:
    st.header("Model Info")
    tm = meta.get("test_metrics", {})
    if tm:
        st.metric("Test MAE",  f"${tm.get('MAE',  0):.5f}")
        st.metric("Test RMSE", f"${tm.get('RMSE', 0):.5f}")
        st.metric("Test R²",   f"{tm.get('R2',    0):.4f}")
        st.metric("Test MAPE", f"{tm.get('MAPE',  0):.2f}%")
    st.divider()
    st.caption(f"Export date: {meta.get('export_date','–')}")
    st.caption(f"Features: {meta.get('n_features','–')}")
    ser = meta.get("serialisation", {})
    if ser:
        st.caption(f"sklearn {ser.get('sklearn','–')} / joblib {ser.get('joblib','–')}")

# ── Fetch data ────────────────────────────────────────────────────────────
st.subheader("📈 Latest DOGE/USD Data")
raw_df = fetch_doge(days=90) or synthetic_data(90)

st.line_chart(raw_df["close"].rename("Close (USD)"))

# ── Build features & predict ──────────────────────────────────────────────
feat_df = build_features(raw_df)

if feat_df.empty:
    st.error("Not enough data to build features. Fetch more days.")
    st.stop()

# Check all required features are present
missing_cols = [c for c in feature_cols if c not in feat_df.columns]
if missing_cols:
    st.error(f"Missing feature columns: {missing_cols}\nThis means the deployment feature engineering is out of sync with training.")
    st.stop()

latest_row    = feat_df.iloc[[-1]][feature_cols]
latest_scaled = scaler.transform(latest_row)
predicted     = model.predict(latest_scaled)[0]
current_price = raw_df["close"].iloc[-1]
delta         = predicted - current_price
pct_change    = delta / current_price * 100

# ── Display prediction ─────────────────────────────────────────────────────
st.subheader("🔮 Prediction")
col1, col2, col3 = st.columns(3)
col1.metric("Current Close",    f"${current_price:.5f}")
col2.metric("Predicted Tomorrow", f"${predicted:.5f}", f"{pct_change:+.2f}%")
col3.metric("Expected Δ",       f"${delta:+.5f}")

st.divider()

# ── Feature values used ────────────────────────────────────────────────────
with st.expander("📊 Feature values used for this prediction"):
    disp = latest_row.T.rename(columns={latest_row.index[0]: "value"})
    st.dataframe(disp.style.format("{:.6f}"), height=600)

st.caption(
    "⚠️ This is a machine-learning model output, not financial advice. "
    "Crypto markets are highly volatile."
)
